
export const bannedPhrases = [
    "This depends on how it is applied",
    "Some even see it this way", // ADD THIS LINE
    'diverse perspectives',
    'inclusive environments',
    'skilled communication',
    'significant advancement',
    'essential component',
    'bridge cultural differences',
    'rationale behind this shift',
    'proved more challenging than anticipated',
    'promoting collaboration',
    'in recent years',
    'a major concern',
    'as research suggests',
    'what this means is',
    'on top of things',
    'that’s for sure',
    'clash into a chance',
    'clash into an opportunity',
    'clash into a chance for growth',
    'a win-win',
    'chill out',
    'a no-brainer',
    'big picture view',
    'drill down',
    'move the needle',
    'level the playing field',
    'raise the bar',
    'push the envelope',
    'back to the drawing board',
    'keep an eye on',
    'step up to the plate',
    'get the ball rolling',
    'out of the box',
    'low-hanging fruit',
    'take it to the next level',
    'think outside the box',
    'get on the same page',
    'let’s take',
    'individuals’ve got a leader',
    'goes hand in hand with',
    'have a knack for',
    "at play",
    "increasingly clear",
    "navigating the complexities",
    "crucial factor",
    "no longer simply about",
    "and to be fair",
    "has emerged as a vital element",
    "prove its significance",
    "ever-changing landscape",

      // 🧠 Academic abstractions
      "plays a major role",
      "plays a key role",
      "in today's world",
      "in modern society",
      "a wide range of",
      "various factors",
      "the ever-changing landscape",
      "due to the fact that",
      "it is important to note that",
      "it should be noted that",
    
      // 💡 Exaggerated claims
      "invaluable insight",
      "profound impact",
      "significant implications",
      "crucial to the success",
      "transformative experience",
      "revolutionized the way",
      "groundbreaking discovery",
    
      // 🤖 GPT-sounding transitions & setups
      "in conclusion",
      "to summarize",
      "in order to",
      "furthermore, it is important to",
      "thus, it can be seen that",
      "as a result, it can be concluded that",
      "this highlights the importance of",
      "it can be argued that",
      "this essay will discuss",
      "this paper aims to",
    
      // 💬 Fluff and filler
      "it goes without saying that",
      "needless to say",
      "it is widely believed that",
      "it is commonly known that",
      "many experts agree that",
    
      // 🎓 Clichéd intro phrases
      "since the dawn of time",
      "throughout history",
      "ever since humans began",
      "with the advent of technology",
      "in the digital age",
    
      // 🧪 Overused scientific hedges
      "research suggests that",
      "studies have shown that",
      "according to recent studies",
      "a growing body of evidence indicates",
      "data clearly indicates that",

      // Sentence Structures
      "this essay will explore",
      "the following paragraphs will discuss",
      "it is clear that",
      "this topic is important because",
      "as mentioned earlier",
      "one must consider that",
      "this shows the importance of",
      "it can be concluded that",

    ];
    

  