export const bannedPhrases = [
  "provide a valuable insight",
  "left an indelible mark",
  "play a significant role in shaping",
  "an unwavering commitment",
  "open a new avenue",
  "a stark reminder",
  "play a crucial role in determining",
  "finding a contribution",
  "crucial role in understanding",
  "finding a shed light",
  "gain a comprehensive understanding",
  "conclusion of the study provides",
  "a nuanced understanding",
  "hold a significant",
  "gain significant attention",
  "continue to inspire",
  "provide a comprehensive overview",
  "finding the highlight the importance",
  "endure a legacy",
  "mark a significant",
  "gain a deeper understanding",
  "the multifaceted nature",
  "the complex interplay",
  "study shed light on",
  "need to fully understand",
  "navigate the complex",
  "a serf reminder",
  "the potential to revolutionize",
  "the relentless pursuit",
  "offer a valuable",
  "underscore the importance",
  "a complex multifaceted",
  "the transformative power",
  "today the fast pace of the world",
  'In today’s fast-paced digital landscape',
  'In today’s fast-paced digital world',
  "a significant milestone",
  ' in the digital market',
  "delve deeper into",
  "provide an insight",
  "navigate the challenge",
  "highlight the potential",
  "pose a significant challenge",
  "a unique blend",
  "a crucial development",
  "various fields include",
  "commitment to excellence",
  "sent shockwaves through",
  "emphasize the need",
  "despite the face",
  "understanding the fundamental",
  "leave a lasting",
  "gain a valuable",
  "understand the behavior",
  "broad implications",
  "a prominent figure",
  "study highlights the importance",
  "a significant turning point",
  "curiosity piques",
  "today in the digital age",
  "implication to understand",
  "a beacon of hope",
  "pave the way for the future",
  "finding an important implication",
  "understand the complexity",
  "meticulous attention to",
  "add a layer",
  "the legacy of life",
  "identify the area of improvement",
  "aim to explore",
  "highlight the need",
  "provide the text",
  "conclusion of the study demonstrates",
  "a multifaceted approach",
  "provide a framework to understand",
  "present a unique challenge",
  "highlight the significance",
  "add depth to",
  "a significant stride",
  "gain an insight",
  "underscore the need",
  "the importance to consider",
  "offer a unique perspective",
  "contribute to understanding",
  "a significant implication",
  "despite the challenge faced",
  "enhances the understanding",
  "make an informed decision in regard to",
  "the target intervention",
  "require a careful consideration",
  "essential to recognize",
  "validate the finding",
  "vital role in shaping",
  "sense of camaraderie",
  "influence various factors",
  "make a challenge",
  "unwavering support",
  "importance of the address",
  "a significant step forward",
  "add an extra layer",
  "address the root cause",
"a profound implication",
"contributes to understanding",
  "This depends on how it is applied",
  "Some even see it this way", // ADD THIS LINE
  'diverse perspectives',
  'inclusive environments',
  'skilled communication',
  'significant advancement',
  'essential component',
  'bridge cultural differences',
  'rationale behind this shift',
  'proved more challenging than anticipated',
  'promoting collaboration',
  'in recent years',
  'a major concern',
  'as research suggests',
  'what this means is',
  'on top of things',
  'that’s for sure',
  'clash into a chance',
  'clash into an opportunity',
  'clash into a chance for growth',
  'a win-win',
  'chill out',
  'a no-brainer',
  'big picture view',
  'drill down',
  'move the needle',
  'level the playing field',
  'raise the bar',
  'push the envelope',
  'back to the drawing board',
  'keep an eye on',
  'step up to the plate',
  'get the ball rolling',
  'out of the box',
  'low-hanging fruit',
  'take it to the next level',
  'think outside the box',
  'get on the same page',
  'let’s take',
  'individuals’ve got a leader',
  'goes hand in hand with',
  "at play",
  "increasingly clear",
  "navigating the complexities",
  "crucial factor",
  "no longer simply about",
  "and to be fair",
  "has emerged as a vital element",
  "prove its significance",
  "ever-changing landscape",
  'In today’s fast-paced world',
  'In today’s',

    // 🧠 Academic abstractions
    "plays a major role",
    "plays a key role",
    "in today's world",
    "in modern society",
    "a wide range of",
    "various factors",
    "the ever-changing landscape",
    "due to the fact that",
    "it is important to note that",
    "it should be noted that",
  
    // 💡 Exaggerated claims
    "invaluable insight",
    "profound impact",
    "significant implications",
    "crucial to the success",
    "transformative experience",
    "revolutionized the way",
    "groundbreaking discovery",
  
    // 🤖 GPT-sounding transitions & setups
    "in conclusion",
    "to summarize",
    "in order to",
    "furthermore, it is important to",
    "thus, it can be seen that",
    "as a result, it can be concluded that",
    "this highlights the importance of",
    "it can be argued that",
    "this essay will discuss",
    "this paper aims to",
  
    // 💬 Fluff and filler
    "it goes without saying that",
    "needless to say",
    "it is widely believed that",
    "it is commonly known that",
    "many experts agree that",
  
    // 🎓 Clichéd intro phrases
    "since the dawn of time",
    "throughout history",
    "ever since humans began",
    "with the advent of technology",
    "in the digital age",
  
    // 🧪 Overused scientific hedges
    "research suggests that",
    "studies have shown that",
    "according to recent studies",
    "a growing body of evidence indicates",
    "data clearly indicates that",

    // Sentence Structures
    "this essay will explore",
    "the following paragraphs will discuss",
    "it is clear that",
    "this topic is important because",
    "as mentioned earlier",
    "one must consider that",
    "this shows the importance of",
    "it can be concluded that"
  ];