export const protectedKeywords = [
  'stakeholder analysis', 'market penetration', 'disruptive innovation',
  'value proposition', 'leveraged buyout',
  'recursive algorithm', 'object inheritance', 'stack overflow',
  'regression testing', 'latency optimization',
  'conditioned response', 'cognitive dissonance', 'neuroplasticity',
  'habituation', 'dissociative state',
  'differential diagnosis', 'iatrogenic effect', 'idiopathic condition',
  'contraindication', 'comorbidity',
  'proximate cause', 'statutory interpretation', 'burden of proof',
  'estoppel', 'jurisprudence',
  'factor of safety', 'stress concentration', 'material fatigue',
  'thermal gradient', 'tolerance stack-up',
  'unreliable narrator', 'intertextuality', 'metafiction',
  'ekphrasis', 'postcolonial critique',
  'stereoisomerism', 'nucleophilic substitution', 'redox potential',
  'steric hindrance', 'molecular chirality',
  'scaffolded instruction', 'formative assessment', 'differentiated learning',
  'zone of proximal development', 'metacognition',
  'arbitrage opportunity', 'yield curve inversion', 'duration matching',
  'black swan event', 'contango market',
  'cultural capital', 'social stratification', 'dramaturgical analysis',
  'anomie', 'ethnomethodology',
  'quantum entanglement', 'laminar flow', 'relativistic time dilation',
  'fermion degeneracy', 'adiabatic process',
  'omnichannel strategy', 'customer journey mapping', 'psychographic segmentation',
  'share of wallet', 'brand equity dilution',
  'material culture', 'kinship systems', 'liminal spaces',
  'cultural relativism', 'ethnographic fieldwork',
  'morphological derivation', 'pragmatic implicature', 'syntactic parsing',
  'phonemic contrast', 'generative grammar',
  'stratigraphic context', 'taphonomic processes', 'seriation dating',
  'provenience', 'palimpsest deposition',
  'deadweight loss', 'opportunity cost', 'indifference curve',
  'pareto efficiency', 'veblen goods',
  'synaptic pruning', 'long-term potentiation', 'salience network',
  'neuronal reuptake', 'default mode network',
  'spatial hierarchy', 'curtain wall system', 'phenomenological experience',
  'tectonics', 'program adjacency',
  'bioaccumulation', 'riparian buffer', 'trophic cascade',
  'carbon sequestration', 'ecological succession'
];
